name: Python code format (autopep8)
on: pull_request

jobs:
  autopep8-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: autopep8 check and fix
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --diff --aggressive --aggressive .

      - name: warning autopep8
        if: steps.autopep8.outputs.exit-code == 2
        run: echo "::warning ::There are some formats error (autopep8 2 level agressive) in pull request. A bot will fix this issue when pull request is merged."

   
      - name: Comment PR warning
        if: steps.autopep8.outputs.exit-code == 2
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ':warning: \n There are some formats error (autopep8 2 level agressive) in pull request. A bot will fix this issue when pull request is merged. \n See workflow log to see future changes.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
